name: Validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

  push:
    branches:
      - 'feature/**'

jobs:
  validation:
    uses: ./.github/workflows/reusable/reusable-validation.yml